<template>
  <div>
    <SearchContent></SearchContent>
    <contentBox :boxInfo="totalInfo.box1"></contentBox>
    <contentBox :boxInfo="totalInfo.box2"></contentBox>
    <contentBox :boxInfo="totalInfo.box3"></contentBox>
  </div>
</template>

<script>
import SearchContent from "../components/searchContent.vue";
import ContentBox from "../components/contentBox.vue";
export default {
  name: "home",
  data() {
    return {
      msg: {
        info: "hello",
      },

      totalInfo: {
        box1: {
          title: {
            name: "高薪全职",
            des: "全职招聘 快来选择",
            more: "查看更多全职",
          },
          head_recommend: [
            "服务员",
            "送餐员",
            "餐饮工",
            "促销导购",
            "销售话务",
            "客服文员",
            "审核录入",
            "哈哈哈哈",
          ],
          jobList: [
            {
              title: "辅导员",
              desc: "高薪招聘学校辅导员",
              type: "全职",
              location: "成都",
              need: 10,
              salary: "4k-12k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "计算机学院教师",
              desc: "高薪招聘计算机学院教师",
              type: "全职",
              location: "成都",
              need: 5,
              salary: "4k-12k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "会计学院教师",
              desc: "高薪招聘会计学院教师",
              type: "全职",
              location: "成都",
              need: 7,
              salary: "4k-12k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "机械学院教师",
              desc: "高薪招聘机械学院教师",
              type: "全职",
              location: "成都",
              need: 7,
              salary: "4k-12k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "艺术学院教师",
              desc: "高薪招聘艺术学院教师",
              type: "全职",
              location: "成都",
              need: 7,
              salary: "3k-10k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "土木学院教师",
              desc: "高薪招聘土木学院教师",
              type: "全职",
              location: "成都",
              need: 10,
              salary: "4k-12k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "教务处工作人员",
              desc: "招聘学院教务处工作人员",
              type: "全职",
              location: "成都",
              need: 7,
              salary: "4k-12k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "团委办公人员",
              desc: "招聘团委办公人员",
              type: "兼职",
              location: "成都",
              need: 1,
              salary: "2k-8k",
              salary_type: "月结",
              cpy: "XXXXX公司/XXXXX学校",
              demand: "这里放招聘单位XXXXX公司/XXXXX学校要求",
              cpy_info:
                "XXXXX公司/XXXXX学校XXXXXXXXXXXXXXXXXX，XXXXXXXXXXXXXXXXXXXXXXXXXXX",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
          ],
        },
        box2: {
          title: {
            name: "靠谱兼职",
            des: "靠谱兼职 快来挑选",
            more: "查看更多兼职",
          },
          head_recommend: [
            "传单派发",
            "服务员",
            "问卷调查",
            "打包分拣",
            "充场",
            "审核录入",
            "餐饮工",
            "展会协助",
          ],
          jobList: [
            {
              title: "服务员",
              desc: "餐厅服务员",
              type: "兼职",
              location: "成都",
              need: 10,
              salary: "30",
              salary_type: "日结",
              cpy: "兼识餐厅/兼识食堂/兼识快餐",
              demand: "这里放招聘单位兼识兼识XX要求",
              cpy_info: "服务员单位/公司的详细介绍信息",
              onQuery: 5,
              remarkrate: 33,
              handleSpeed: "1-2",
              point: 2.5,
            },
            {
              title: "餐饮工",
              desc: "餐厅餐饮工",
              type: "兼职",
              location: "成都",
              need: 5,
              salary: "30",
              salary_type: "日结",
              cpy: "兼识餐厅/兼识食堂/兼识快餐",
              demand: "这里放招聘单位兼识兼识XX要求",
              cpy_info: "餐饮工公司单位的详细介绍",
              onQuery: 5,
              remarkrate: 88,
              handleSpeed: "1-2",
              point: 3.7,
            },
            {
              title: "防疫执勤",
              desc: "防疫执勤",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "30",
              salary_type: "日结",
              cpy: "兼识餐厅/兼识食堂/兼识快餐",
              demand: "这里放招聘单位兼识兼识XX要求",
              cpy_info: "防疫单位的详细介绍信息兼识兼识",
              onQuery: 53,
              remarkrate: 26,
              handleSpeed: "1-2",
              point: 4.5,
            },
            {
              title: "传单派发",
              desc: "在兼识派发宣传传单",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "30",
              salary_type: "日结",
              cpy: "兼识餐厅/兼识食堂/兼识快餐",
              demand: "这里放招聘单位兼识兼识XX要求",
              cpy_info: "传单派发单位的详细介绍信息",
              onQuery: 3,
              remarkrate: 56,
              handleSpeed: "2-3",
              point: 3.4,
            },
            {
              title: "传真打印兼职",
              desc: "在后街传真打印兼职",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "35",
              salary_type: "日结",
              cpy: "印务公司兼识",
              demand: "这里放招聘单位兼识兼识XX要求",
              cpy_info: "在后街传真打印兼职单位的详细介绍信息",
              onQuery: 3,
              remarkrate: 56,
              handleSpeed: "2-3",
              point: 3.4,
            },
            {
              title: "肯德基兼职服务员",
              desc: "肯德基兼职服务员兼识兼识",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "35",
              salary_type: "日结",
              cpy: "印务公司兼识",
              demand: "肯德基兼职服务员兼识XX的详细要求",
              cpy_info: "肯德基兼职服务员兼识兼识详细介绍信息",
              onQuery: 3,
              remarkrate: 56,
              handleSpeed: "2-3",
              point: 3.4,
            },
            {
              title: "游乐园工作人员",
              desc: "游乐园工作人员兼识XX",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "35",
              salary_type: "日结",
              cpy: "印务公司兼识",
              demand: "游乐园工作人员兼识兼识X的详细要求",
              cpy_info: "游乐园工作人员公司兼识兼识XX详细介绍信息",
              onQuery: 3,
              remarkrate: 56,
              handleSpeed: "2-3",
              point: 3.4,
            },
            {
              title: "烧烤店兼职员工",
              desc: "烧烤店兼职员工兼识XX",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "35",
              salary_type: "日结",
              cpy: "印务公司兼识",
              demand: "烧烤店兼职员工兼识XX的详细要求",
              cpy_info: "烧烤店兼职员工公司兼识兼识X详细介绍信息",
              onQuery: 3,
              remarkrate: 56,
              handleSpeed: "2-3",
              point: 3.4,
            },
            {
              title: "动力小子快递",
              desc: "动力小子快递兼识兼识X",
              type: "兼职",
              location: "成都",
              need: 7,
              salary: "35",
              salary_type: "日结",
              cpy: "印务公司兼识",
              demand: "动力小子快递XX的详细要求",
              cpy_info: "动力小子快递公司兼识兼识X详细介绍信息",
              onQuery: 3,
              remarkrate: 56,
              handleSpeed: "2-3",
              point: 3.4,
            },
          ],
        },
        box3: {
          title: {
            name: "大厂直达",
            des: "大厂直聘，快来投递",
            more: "更多大型企业",
          },
          head_recommend: [
            "百度",
            "阿里",
            "腾讯",
            "京东",
            "美团",
            "微软",
            "谷歌",
            "亚马逊",
          ],
          jobList: [
            {
              title: "前端开发工程师",
              desc: "美团前端开发工程师",
              type: "全职",
              location: "成都",
              need: 10,
              salary: "20k-30k",
              salary_type: "月结",
              cpy: "美团",
              demand: "这里放招聘单位美团的要求",
              cpy_info: "美团公司/单位的介绍信息",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "Java后端开发工程师",
              desc: "字节跳动后端开发工程师",
              type: "全职",
              location: "北京",
              need: 7,
              salary: "20k-30k",
              salary_type: "月结",
              cpy: "字节跳动",
              demand: "这里放招聘单位字节跳动的要求",
              cpy_info: "字节跳动的介绍信息",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "测试开发工程师",
              desc: "百度测试开发工程师",
              type: "全职",
              location: "上海",
              need: 7,
              salary: "15k-25k",
              salary_type: "月结",
              cpy: "百度",
              demand: "这里放招聘单位百度的要求",
              cpy_info: "百度公司的介绍信息",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
            {
              title: "运维工程师",
              desc: "阿里运维工程师",
              type: "全职",
              location: "成都",
              need: 12,
              salary: "15k-25k",
              salary_type: "月结",
              cpy: "阿里",
              demand: "这里放招聘单位阿里的要求",
              cpy_info: "阿里公司的介绍信息",
              onQuery: 5,
              remarkrate: 66,
              handleSpeed: "1-2",
              point: 5.0,
            },
          ],
        },
      },
    };
  },
  components: {
    SearchContent,
    ContentBox,
  },
};
</script>

<style>
</style>